<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SecretsManager\SecretsManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SecretsManager" Version="3.7.400.65" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SecretsManager.AwsSecretsManager.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
