<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SecretsManager\SecretsManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SecretsManager.Vault.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
