<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SecretsManager\SecretsManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.9.0" />
    <PackageReference Include="Azure.Identity" Version="1.19.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SecretsManager.AzureKeyVault.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
