<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SecretsManager\SecretsManager.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.FileSystem\SecretsManager.FileSystem.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.AzureKeyVault\SecretsManager.AzureKeyVault.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.Scaleway\SecretsManager.Scaleway.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.PostgreSql\SecretsManager.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.OVH\SecretsManager.OVH.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.AwsSecretsManager\SecretsManager.AwsSecretsManager.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.OracleVault\SecretsManager.OracleVault.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.GoogleSecretManager\SecretsManager.GoogleSecretManager.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.Passbolt\SecretsManager.Passbolt.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.AliyunKms\SecretsManager.AliyunKms.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.IBMCloudSecretsManager\SecretsManager.IBMCloudSecretsManager.csproj" />
    <ProjectReference Include="..\..\src\SecretsManager.TencentCloud\SecretsManager.TencentCloud.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="configs\*.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
